/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.
   The TypeScript is the source and is what the 67 tests in
   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */
"use strict";
/**
 * lib/errors.ts -- refusals that answer the same way whatever they are refusing.
 *
 * THE PROPERTY: a refusal must not tell the caller whether the row exists. If
 * "not found" and "not yours" differ by one byte, the API is an existence
 * oracle -- point it at a list of uuids and it enumerates another league's
 * teams without ever returning one of their rows. So there is a fixed list of
 * responses here, each a flat string, and nothing from Postgres reaches the
 * wire: not `message`, not `detail`, not `constraint`, not `hint`, not `where`,
 * not the parameters that were echoed into a raise.
 *
 * Postgres is helpful in exactly the way that hurts here. A check violation
 * names the constraint and prints the row; a raise inside a security definer
 * function quotes its arguments ("role x is not a team role", "invitation
 * expired on ..."); a unique violation prints the colliding key. All of that is
 * a description of data the caller was just refused.
 *
 * The mapping:
 *   42501  insufficient_privilege -> 403 forbidden   (RLS, a missing EXECUTE
 *                                                     grant, or a raise from a
 *                                                     definer function)
 *   23505  unique_violation       -> 409 conflict
 *   23514/23503/23502/23P01       -> 400 rejected    (constraint contents dropped)
 *   22023/22P02/22001/22007/22008 -> 400 rejected    (bad argument, bad uuid)
 *   40001/40P01                   -> 409 conflict    (serialisation, retryable)
 *   57014  query_canceled         -> 503 unavailable (statement timeout)
 *   anything else                 -> 500 server error, logged, never described
 *
 * The full error goes to the server log, where the caller cannot read it. That
 * is the only copy anybody needs.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.rejected = exports.forbidden = exports.notFound = exports.ApiError = void 0;
exports.toResponse = toResponse;
exports.flatResponse = flatResponse;
/** The complete vocabulary of refusals. Flat, and identical between causes. */
const FLAT = {
    400: "rejected",
    401: "unauthorized",
    403: "forbidden",
    404: "not found",
    409: "conflict",
    500: "server error",
    501: "not implemented",
    503: "unavailable",
};
class ApiError extends Error {
    status;
    /** Overrides the flat message. Only ever set to another constant in this repo. */
    flat;
    constructor(status, flat) {
        super(flat ?? FLAT[status]);
        this.name = "ApiError";
        this.status = status;
        this.flat = flat ?? FLAT[status];
    }
}
exports.ApiError = ApiError;
const notFound = () => new ApiError(404);
exports.notFound = notFound;
const forbidden = () => new ApiError(403);
exports.forbidden = forbidden;
const rejected = () => new ApiError(400);
exports.rejected = rejected;
function pgCode(err) {
    if (typeof err !== "object" || err === null)
        return null;
    const code = err.code;
    return typeof code === "string" ? code : null;
}
function statusForPg(code) {
    switch (code) {
        case "42501": // insufficient_privilege: RLS refused, or no EXECUTE grant
            return 403;
        case "23505": // unique_violation
        case "40001": // serialization_failure
        case "40P01": // deadlock_detected
            return 409;
        case "23514": // check_violation
        case "23503": // foreign_key_violation
        case "23502": // not_null_violation
        case "23P01": // exclusion_violation
        case "22023": // invalid_parameter_value -- our own raises use this
        case "22P02": // invalid_text_representation (a malformed uuid)
        case "22001": // string_data_right_truncation
        case "22007": // invalid_datetime_format
        case "22008": // datetime_field_overflow
            return 400;
        case "57014": // query_canceled -- statement_timeout
            return 503;
        default:
            return 500;
    }
}
/**
 * Turn anything thrown into the response the caller sees. The only branch that
 * reads the error at all reads its `code`; the text is logged, never returned.
 */
function toResponse(err) {
    let status = 500;
    if (err instanceof ApiError) {
        status = err.status;
        return flatResponse(status, err.flat);
    }
    const code = pgCode(err);
    if (code) {
        status = statusForPg(code);
        // Server-side only. A 500 with no cause in the log is how a real bug hides.
        console.error(`[api] postgres ${code} -> ${status}:`, err.message ?? "", err.constraint ? `constraint=${err.constraint}` : "");
    }
    else {
        console.error("[api] unhandled:", err);
    }
    return flatResponse(status, FLAT[status]);
}
function flatResponse(status, flat) {
    return new Response(JSON.stringify({ error: flat }), {
        status,
        headers: {
            "content-type": "application/json; charset=utf-8",
            "cache-control": "no-store",
        },
    });
}
