/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.
   The TypeScript is the source and is what the 67 tests in
   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */
"use strict";
/**
 * lib/http.ts -- the thin shell around a handler: parse, run, and turn any
 * throw into a flat refusal.
 *
 * There is deliberately no authorization helper in this file. No
 * `requireRole()`, no `assertTeamMember()`, nothing that reads a membership. A
 * handler that needed one would be a handler doing the database's job, and the
 * database already refuses on its own. What is here is input handling: is this
 * JSON, is that path segment a uuid, and what shape does the answer take.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.route = route;
exports.json = json;
exports.readJson = readJson;
exports.pathUuid = pathUuid;
exports.str = str;
exports.optStr = optStr;
exports.optUuid = optUuid;
exports.optInt = optInt;
exports.optObject = optObject;
exports.optInterval = optInterval;
const errors_1 = require("./errors");
const session_1 = require("./session");
/** Every exported route goes through this, so nothing can throw to the client. */
function route(fn) {
    return async (req, ctx) => {
        try {
            return await fn(req, ctx);
        }
        catch (err) {
            return (0, errors_1.toResponse)(err);
        }
    };
}
function json(data, status = 200, headers = {}) {
    return new Response(JSON.stringify(data), {
        status,
        headers: {
            "content-type": "application/json; charset=utf-8",
            // Nothing here is cacheable: every response is scoped to one caller.
            "cache-control": "no-store",
            ...headers,
        },
    });
}
const MAX_BODY_BYTES = 1_000_000;
async function readJson(req) {
    const raw = await req.text();
    if (raw.length > MAX_BODY_BYTES)
        throw new errors_1.ApiError(400);
    if (raw.trim() === "")
        return {};
    let parsed;
    try {
        parsed = JSON.parse(raw);
    }
    catch {
        throw new errors_1.ApiError(400);
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed))
        throw new errors_1.ApiError(400);
    return parsed;
}
/**
 * A path id that is not a uuid is answered exactly like a uuid that names
 * nothing: 404. Letting a malformed id fall through to Postgres would come back
 * as a 400 and hand the caller a way to tell "wrong shape" from "not yours".
 */
async function pathUuid(ctx, key) {
    const params = await ctx.params;
    const v = params[key];
    if (!(0, session_1.isUuid)(v))
        throw new errors_1.ApiError(404);
    return v;
}
function str(body, key) {
    const v = body[key];
    if (typeof v !== "string" || v.trim() === "")
        throw new errors_1.ApiError(400);
    return v.trim();
}
function optStr(body, key) {
    const v = body[key];
    if (v === undefined || v === null)
        return null;
    if (typeof v !== "string")
        throw new errors_1.ApiError(400);
    const t = v.trim();
    return t === "" ? null : t;
}
function optUuid(body, key) {
    const v = optStr(body, key);
    if (v === null)
        return null;
    if (!(0, session_1.isUuid)(v))
        throw new errors_1.ApiError(400);
    return v;
}
function optInt(body, key) {
    const v = body[key];
    if (v === undefined || v === null)
        return null;
    if (typeof v !== "number" || !Number.isInteger(v))
        throw new errors_1.ApiError(400);
    return v;
}
function optObject(body, key) {
    const v = body[key];
    if (v === undefined || v === null)
        return null;
    if (typeof v !== "object" || Array.isArray(v))
        throw new errors_1.ApiError(400);
    return v;
}
/**
 * An interval, kept as text and handed to Postgres to parse -- `interval '14
 * days'` is a type the database already validates, and app.issue_invite()
 * already refuses anything outside 0..90 days. Bounded here only so a caller
 * cannot post a megabyte of it.
 */
function optInterval(body, key) {
    const v = optStr(body, key);
    if (v === null)
        return null;
    if (v.length > 40)
        throw new errors_1.ApiError(400);
    return v;
}
