/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.
   The TypeScript is the source and is what the 67 tests in
   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */
"use strict";
/**
 * lib/session.ts -- where identity comes from, and the only place it comes from.
 *
 * IDENTITY COMES FROM THE SESSION, NEVER FROM THE REQUEST BODY. A `team_id` in
 * a payload is a hint about what to fetch; it is never proof of who is asking.
 * Every handler in lib/routes builds its Caller here and nowhere else, so there
 * is no path by which a field in a JSON body becomes an identity claim.
 *
 * The token is an HMAC-SHA256 over a compact JSON payload -- a stand-in with
 * exactly the shape of the thing it stands in for. In production the claims
 * arrive in a Supabase JWT and PostgREST puts them in request.jwt.claims; here
 * they arrive in a cookie this file signed. Either way the API's job is the
 * same: verify, then hand `sub` and `email` to the database as app.user_id and
 * app.user_email. 0002_schema.sql and 0004_auth.sql already say those two GUCs map 1:1 to
 * auth.uid() and auth.email(), so swapping this file for a JWT verifier changes
 * nothing above it.
 *
 * FAIL CLOSED. A missing secret, a missing token, a bad signature, an expired
 * payload, a `sub` that is not a uuid: all of them produce the anonymous
 * caller, not an error and not a partial identity. The database is then asked
 * the question anyway, and answers with nothing -- which is the point. An
 * unauthenticated request is refused by RLS and by the missing EXECUTE grants
 * on pd_anon, not by an `if` in a handler.
 *
 * THE BOYS' WORD is not a session and deliberately does not get one. It arrives
 * as two headers, is never stored, and is re-verified against player_words on
 * every single statement by app.player_team_id(). That is what makes rotation
 * bite immediately: there is no ticket to expire.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SESSION_COOKIE = void 0;
exports.isUuid = isUuid;
exports.mintSession = mintSession;
exports.verifySession = verifySession;
exports.callerFrom = callerFrom;
exports.sessionCookie = sessionCookie;
exports.clearedSessionCookie = clearedSessionCookie;
const node_crypto_1 = require("node:crypto");
const db_1 = require("./db");
const errors_1 = require("./errors");
exports.SESSION_COOKIE = "hub_session";
const DEFAULT_TTL_SECONDS = 60 * 60 * 12;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function isUuid(v) {
    return typeof v === "string" && UUID_RE.test(v);
}
function secret() {
    const s = process.env.HUB_SESSION_SECRET;
    if (!s || s.length < 16)
        return null;
    return Buffer.from(s, "utf8");
}
const b64u = (b) => b.toString("base64url");
function sign(payload, key) {
    return b64u((0, node_crypto_1.createHmac)("sha256", key).update(payload).digest());
}
/**
 * Mint a session. Called by POST /api/session, which is itself gated: without
 * an identity provider wired up there is no credential to check, so that route
 * refuses to run outside development. See lib/routes/session.ts.
 */
function mintSession(sub, email, ttlSeconds = DEFAULT_TTL_SECONDS) {
    const key = secret();
    if (!key)
        throw new errors_1.ApiError(501);
    if (!isUuid(sub))
        throw new errors_1.ApiError(400);
    const claims = {
        sub,
        email: email ? email.trim().toLowerCase() : null,
        exp: Math.floor(Date.now() / 1000) + ttlSeconds,
    };
    const body = b64u(Buffer.from(JSON.stringify(claims), "utf8"));
    return `${body}.${sign(body, key)}`;
}
/** Verify a token. Any doubt at all returns null, which means "anonymous". */
function verifySession(token) {
    const key = secret();
    if (!key || !token)
        return null;
    const dot = token.indexOf(".");
    if (dot <= 0 || dot === token.length - 1)
        return null;
    const body = token.slice(0, dot);
    const mac = token.slice(dot + 1);
    const expected = Buffer.from(sign(body, key), "utf8");
    const given = Buffer.from(mac, "utf8");
    if (expected.length !== given.length)
        return null;
    if (!(0, node_crypto_1.timingSafeEqual)(expected, given))
        return null;
    try {
        const claims = JSON.parse(Buffer.from(body, "base64url").toString("utf8"));
        if (typeof claims !== "object" || claims === null)
            return null;
        const c = claims;
        if (!isUuid(c.sub))
            return null;
        if (typeof c.exp !== "number" || c.exp * 1000 <= Date.now())
            return null;
        const email = typeof c.email === "string" && c.email.includes("@") ? c.email.toLowerCase() : null;
        return { sub: c.sub, email, exp: c.exp };
    }
    catch {
        return null;
    }
}
function cookieValue(header, name) {
    if (!header)
        return null;
    for (const part of header.split(";")) {
        const eq = part.indexOf("=");
        if (eq < 0)
            continue;
        if (part.slice(0, eq).trim() !== name)
            continue;
        return decodeURIComponent(part.slice(eq + 1).trim());
    }
    return null;
}
/**
 * The one function that decides who is asking. Reads a cookie, a bearer header
 * and the two boys'-word headers -- and nothing else. It never touches the body.
 */
function callerFrom(req) {
    const team = req.headers.get("x-player-team");
    const word = req.headers.get("x-player-word");
    if (isUuid(team) && word && word.trim() !== "") {
        // The word is a read credential for one team and is not combined with an
        // account: presenting it asks the database "what may this word see".
        return (0, db_1.asPlayer)(team, word.trim());
    }
    const auth = req.headers.get("authorization");
    const bearer = auth && /^bearer /i.test(auth) ? auth.slice(7).trim() : null;
    const claims = verifySession(bearer ?? cookieValue(req.headers.get("cookie"), exports.SESSION_COOKIE));
    return claims ? (0, db_1.asUser)(claims.sub, claims.email) : db_1.ANON;
}
function sessionCookie(token, maxAgeSeconds = DEFAULT_TTL_SECONDS) {
    return [
        `${exports.SESSION_COOKIE}=${encodeURIComponent(token)}`,
        "Path=/",
        "HttpOnly",
        "SameSite=Lax",
        "Secure",
        `Max-Age=${maxAgeSeconds}`,
    ].join("; ");
}
function clearedSessionCookie() {
    return `${exports.SESSION_COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0`;
}
