/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.
   The TypeScript is the source and is what the 67 tests in
   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TIERS = void 0;
exports.TIERS = {
    platform: {
        name: "Master hub",
        who: "us",
        blurb: "Every league on the platform. This is the only place that sees across tenants, which is why it is the smallest surface in the product.",
        actions: [
            { label: "Create a league", detail: "Name it, set its ruleset, open its first admin seat.", fn: "app.create_league" },
            { label: "Invite a league admin", detail: "One email, one league. They build out their own teams from there.", fn: "app.platform_invite_admin" },
            { label: "See every league", detail: "Names, team counts, seats used \u2014 and counts of children, never their names.", fn: "app.platform_leagues" },
            { label: "Suspend a league", detail: "Billing lapsed or the contract ended. Refuses new seats; deletes nothing, and the coach keeps editing his book.", fn: "app.suspend_league", destructive: true },
        ],
    },
    league: {
        name: "League hub",
        who: "the board",
        blurb: "One league. Its teams, its coaches, its rulebook, and the record of who changed what.",
        actions: [
            { label: "Add a team", detail: "A team in this league, for a season.", fn: "app.create_team", needsSchema: true },
            { label: "Invite a head coach", detail: "One email, one team, one role. Invite-only — nobody joins a team they were not sent to.", fn: "app.issue_invite" },
            { label: "Set the league rulebook", detail: "X-man weight, whether field goals are allowed, minimum plays. Data, not constants.", fn: "leagues.ruleset" },
            { label: "Read the audit log", detail: "Every grant, revocation and invite. Insert-only — it cannot be doctored.", fn: "auth_events" },
            { label: "Remove a child on request", detail: "A parent asks. The player goes; every play he was in keeps its shape and reads a jersey number.", fn: "app.tombstone_player", destructive: true },
        ],
    },
    team: {
        name: "Coach hub",
        who: "a head coach",
        blurb: "One team. His staff, his roster, his book — and the word the boys use to look at it.",
        actions: [
            { label: "Invite an assistant", detail: "Head coaches only. An assistant cannot staff the team he is on.", fn: "app.issue_invite" },
            { label: "Manage the roster", detail: "Last name and jersey. No photos, no weights — deliberately.", fn: "players" },
            { label: "Rotate the boys' word", detail: "Read-only, one team, no account. Rotating it cuts the old one off on the next request.", fn: "app.rotate_player_word" },
            { label: "Open the playbook", detail: "The designer, the formations, and the engine that runs them.", fn: "plays" },
        ],
    },
    player: {
        name: "Player hub",
        who: "a boy on the team",
        blurb: "One team's playbook, read only, with no account at all. The word his coach gives him IS the credential \u2014 there is no login to forget and no session to expire.",
        actions: [
            { label: "Watch the play run", detail: "Every man walks his own route on one clock, and stops where his block or his tackle happens.", fn: "learn.html" },
            { label: "Line me up", detail: "Where does this spot stand? Tap the field; it scores the tap in yards.", fn: "learn.html" },
            { label: "My job", detail: "Multiple choice from the written jobs \u2014 then who he is across from, what that man will try, and how he beats him.", fn: "learn.html" },
            { label: "Nothing else", detail: "No roster he can edit, no other team he can see, and no way to write anything. pd_anon holds no EXECUTE on any staff function.", fn: "app.player_team_id" },
        ],
    },
};
