/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.
   The TypeScript is the source and is what the 67 tests in
   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */
"use strict";
/**
 * lib/routes/coach.ts -- one team, everything a coach's screen needs.
 *
 * ONE ROUND TRIP, ON PURPOSE. The other route modules are one query per
 * endpoint, which is right for an API. This is right for a phone on a practice
 * field: the coach hub draws staff, roster, consent state, the boys' word and
 * the playbook, and doing that in five requests over a bad connection means
 * five chances to half-draw.
 *
 * NOTHING HERE DECIDES ANYTHING. There is no `if (role === 'head')` in this
 * file. Every query runs as the caller and the database refuses what it
 * refuses -- app.may_staff_team() for the staffing verbs, RLS for the reads.
 * What this file DOES report is what the database would allow, so the screen can
 * grey a button rather than offer it and then apologise. That is a hint, not a
 * gate: pressing it anyway still goes through the same refusal.
 *
 * THE ROSTER IS THE CONSENT AUDIT, not a plain select. app.consent_audit_team()
 * is the one that knows which slots are still a jersey number waiting on a
 * guardian, which names are backed by a live consent, and which were collected
 * before any of that existed. A coach's roster screen that cannot show him
 * that is a screen that lets him believe he is compliant.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.inviteStaff = exports.rotateTeamWord = exports.addPlayer = exports.teamOverview = void 0;
const db_1 = require("../db");
const errors_1 = require("../errors");
const http_1 = require("../http");
const session_1 = require("../session");
function teamParam(req) {
    const id = new URL(req.url).searchParams.get("team") ?? "";
    if (!(0, session_1.isUuid)(id))
        throw new errors_1.ApiError(400);
    return id;
}
async function teamOr404(tx, teamId) {
    const r = await tx.query(`select t.id, t.name, t.grade, t.league_id,
            l.name as league, l.kind as league_kind,
            s.name as season, s.ends_on::text as season_ends
       from public.teams t
       left join public.leagues l on l.id = t.league_id
       left join public.seasons s on s.id = t.season_id
      where t.id = $1`, [teamId]);
    const row = r.rows[0];
    // A team he cannot see and a team that does not exist are the same answer.
    // Telling them apart is an oracle for what other leagues contain.
    if (!row)
        throw new errors_1.ApiError(404);
    return row;
}
/** GET /api/team?team=<uuid> */
exports.teamOverview = (0, http_1.route)(async (req) => {
    const teamId = teamParam(req);
    const out = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const team = await teamOr404(tx, teamId);
        const staff = await tx.query(`select user_id::text as user_id, role, created_at::text as created_at
         from public.memberships where team_id = $1
        order by case role when 'head' then 0 when 'assistant' then 1 else 2 end, created_at`, [teamId]);
        // The consent audit rather than a plain roster. See the header.
        let roster = [];
        try {
            const r = await tx.query(`select player_id::text as player_id, jersey, named, roster_ok,
                consent_state, notice_version, plays_naming_him
           from app.consent_audit_team($1)
          order by nullif(regexp_replace(coalesce(jersey,''), '\\D', '', 'g'), '')::int
                     nulls last, jersey, player_id`, [teamId]);
            roster = r.rows;
        }
        catch {
            // A seat that may read players but not the audit still gets a roster.
            const r = await tx.query(`select id::text as player_id, jersey, last, first from public.players
          where team_id = $1
          order by nullif(regexp_replace(coalesce(jersey,''), '\\D', '', 'g'), '')::int
                     nulls last, jersey, last`, [teamId]);
            roster = r.rows.map((p) => ({
                player_id: p.player_id, jersey: p.jersey,
                named: !(p.first === null && /^#/.test(p.last)),
                roster_ok: false, consent_state: "unknown", notice_version: null, plays_naming_him: 0,
            }));
        }
        // Names, separately, and only the ones the caller may already read. The
        // audit deliberately returns jerseys and never names; the screen wants both
        // and RLS decides which rows come back at all.
        const names = await tx.query(`select id::text as id, last, first from public.players where team_id = $1`, [teamId]);
        const byId = new Map(names.rows.map((n) => [n.id, n]));
        const plays = await tx.query(`select id::text as id, slug, updated_at::text as updated_at
         from public.plays where team_id = $1 order by slug`, [teamId]);
        const word = await tx.query(`select count(*) > 0 as has_word, max(expires_at)::text as expires
         from public.player_words where team_id = $1`, [teamId]);
        // What the database would allow, so the screen can grey a button instead of
        // offering it and then apologising. A hint, never a gate.
        // THREE DIFFERENT PERMISSIONS, and conflating them was a real bug in the
        // first draft of the coach hub. `staff` (head, or league admin) governs
        // invitations. The BOYS' WORD does not: 0004_auth.sql says in its own
        // comment that "Dom's seat is assistant and the boys' page is his -- it is
        // a read credential for one team, not a staffing action, which is why it is
        // not restricted to the head the way invitations are." Greying that button
        // on `staff` would have stopped the only user this app has from doing the
        // one thing that is explicitly his.
        const may = await tx.query(`select app.may_staff_team($1) as staff,
              app.may_manage_consent($1) as consent,
              (exists (select 1 from public.memberships m
                        where m.user_id = (select auth.uid()) and m.team_id = $1
                          and m.role in ('head','assistant'))
               or app.may_staff_team($1)) as word`, [teamId]);
        return {
            team,
            staff: staff.rows,
            roster: roster.map((r) => {
                const n = byId.get(r.player_id);
                return { ...r, last: n ? n.last : null, first: n ? n.first : null };
            }),
            plays: plays.rows,
            boys_word: { set: word.rows[0]?.has_word === true, expires: word.rows[0]?.expires ?? null },
            may: {
                staff: may.rows[0]?.staff === true,
                consent: may.rows[0]?.consent === true,
                word: may.rows[0]?.word === true,
            },
        };
    });
    return (0, http_1.json)(out);
});
/**
 * POST /api/team/players?team=<uuid>  { jersey }
 *
 * A NEW SLOT IS A JERSEY NUMBER AND NOTHING ELSE, and that is the product
 * working rather than a limitation. 0007's collection gate refuses to create a
 * named row, so this does not try: it writes the placeholder shape the gate
 * allows, and the name arrives later when a guardian has said yes. A screen
 * that offered a name field here would collect the name first and ask
 * afterwards, which is the thing the whole consent layer exists to prevent.
 */
exports.addPlayer = (0, http_1.route)(async (req) => {
    const teamId = teamParam(req);
    const body = await (0, http_1.readJson)(req);
    const jersey = ((0, http_1.optStr)(body, "jersey") ?? "").trim();
    if (jersey.length > 4)
        throw new errors_1.ApiError(400);
    const out = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        await teamOr404(tx, teamId);
        const r = await tx.query(`insert into public.players (team_id, last, first, jersey)
       values ($1, app.jersey_placeholder($2), null, nullif($2, ''))
       returning id::text as id, jersey, last`, [teamId, jersey]);
        return r.rows[0] ?? null;
    });
    if (!out)
        throw new errors_1.ApiError(500);
    return (0, http_1.json)({ player: out, named: false }, 201);
});
/** POST /api/team/word?team=<uuid> -- rotate the boys' word. */
exports.rotateTeamWord = (0, http_1.route)(async (req) => {
    const teamId = teamParam(req);
    const out = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const r = await tx.query(`select app.rotate_player_word($1, null, null) as word`, [teamId]);
        return r.rows[0]?.word ?? null;
    });
    if (!out)
        throw new errors_1.ApiError(500);
    // shown_once is not decoration: only the sha256 is stored, so this is the
    // only moment the word exists anywhere it can be read.
    return (0, http_1.json)({ team_id: teamId, word: out, shown_once: true });
});
/** POST /api/team/staff?team=<uuid>  { email, role } -- invite a coach. */
exports.inviteStaff = (0, http_1.route)(async (req) => {
    const teamId = teamParam(req);
    const body = await (0, http_1.readJson)(req);
    const email = (0, http_1.str)(body, "email");
    const role = (0, http_1.str)(body, "role");
    const row = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const r = await tx.query(`select invite_id, token
         from app.issue_invite($1, $2, $3::uuid, null::uuid, interval '14 days')`, [email, role, teamId]);
        return r.rows[0] ?? null;
    });
    if (!row)
        throw new errors_1.ApiError(500);
    return (0, http_1.json)({ invite_id: row.invite_id, token: row.token, shown_once: true }, 201);
});
