/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.
   The TypeScript is the source and is what the 67 tests in
   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */
"use strict";
/**
 * lib/routes/platform.ts -- the vendor's four actions, as named in lib/tiers.ts.
 *
 *   Create a league       app.create_league
 *   Invite a league admin app.platform_invite_admin
 *   See every league      app.platform_leagues
 *   Suspend a league      app.suspend_league / app.unsuspend_league
 *
 * NOT ONE OF THESE HANDLERS CHECKS WHETHER THE CALLER IS A PLATFORM OWNER.
 * app.require_platform_owner() is the first line of every one of those
 * functions, and pd_anon holds no EXECUTE on any of them, so an anonymous
 * caller is refused by the privilege check before the function is even entered.
 * A second check here would be a second thing to get wrong, and the only way it
 * could ever differ from the database's answer is by being wrong.
 *
 * WHAT COMES BACK IS THE PRIVACY SPECIFICATION. app.platform_leagues() returns
 * league names, counts and dates -- player_count is an integer and there is no
 * function on this seat that returns a child's name, a jersey, a play slug or a
 * play document. This file adds nothing to that and takes nothing away: it
 * selects the function's own columns, casts the bigint counts to int so JSON
 * carries numbers rather than strings, and hands them on.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.inviteLeagueAdmin = exports.setLeagueStatus = exports.createLeague = exports.listLeagues = void 0;
const db_1 = require("../db");
const http_1 = require("../http");
const errors_1 = require("../errors");
const session_1 = require("../session");
const LEAGUES_SQL = `
  select league_id,
         league_name,
         status,
         plan,
         seats_purchased,
         contract_ends_on,
         season_count::int   as season_count,
         season_first_start,
         season_last_end,
         team_count::int     as team_count,
         coach_seats::int    as coach_seats,
         board_seats::int    as board_seats,
         player_count::int   as player_count,
         play_count::int     as play_count,
         last_play_edit,
         created_at
    from app.platform_leagues()
`;
/** GET /api/platform/leagues */
exports.listLeagues = (0, http_1.route)(async (req) => {
    const rows = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const r = await tx.query(LEAGUES_SQL);
        return r.rows;
    });
    return (0, http_1.json)({ leagues: rows });
});
/** POST /api/platform/leagues -- a sale. */
exports.createLeague = (0, http_1.route)(async (req) => {
    const body = await (0, http_1.readJson)(req);
    const name = (0, http_1.str)(body, "name");
    const ruleset = (0, http_1.optObject)(body, "ruleset");
    const plan = (0, http_1.optStr)(body, "plan");
    const seats = (0, http_1.optInt)(body, "seats");
    const id = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const r = await tx.query(`select app.create_league($1, coalesce($2::jsonb, '{}'::jsonb), coalesce($3, 'trial'), $4) as league_id`, [name, ruleset ? JSON.stringify(ruleset) : null, plan, seats]);
        return r.rows[0]?.league_id ?? null;
    });
    if (!id)
        throw new errors_1.ApiError(500);
    return (0, http_1.json)({ league_id: id }, 201);
});
/**
 * POST /api/platform/leagues/[leagueId]/status  { status, reason? }
 *
 * Suspension refuses new seats and deletes nothing -- the function returns a
 * census of what it left alone, and that census is passed straight through
 * because it is the answer to "what did this do to my league".
 */
exports.setLeagueStatus = (0, http_1.route)(async (req, ctx) => {
    const leagueId = await (0, http_1.pathUuid)(ctx, "leagueId");
    const body = await (0, http_1.readJson)(req);
    const status = (0, http_1.str)(body, "status");
    if (status !== "suspended" && status !== "active")
        throw new errors_1.ApiError(400);
    const reason = (0, http_1.optStr)(body, "reason");
    const result = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const r = status === "suspended"
            ? await tx.query(`select app.suspend_league($1, $2) as result`, [leagueId, reason])
            : await tx.query(`select app.unsuspend_league($1) as result`, [leagueId]);
        return r.rows[0]?.result ?? null;
    });
    return (0, http_1.json)({ result });
});
/**
 * POST /api/platform/invites  { league_id, email, valid_for? }
 *
 * The first admin seat of a brand new league. app.issue_invite() cannot do this
 * -- it wants an admin of the league to authorise it and a new league has none
 * -- which is the correction lib/tiers.ts records.
 *
 * The token comes back in plaintext exactly once, here, and is written to no
 * log: the invites table keeps only its sha256, auth_events records that an
 * invitation was issued and not what it was, and nothing in this repo prints
 * it. Whoever calls this endpoint is the thing that emails it.
 */
exports.inviteLeagueAdmin = (0, http_1.route)(async (req) => {
    const body = await (0, http_1.readJson)(req);
    // Shape-checked here so a malformed id is a 400 whoever sends it, rather than
    // a cast error for the vendor and a 403 for everybody else.
    const leagueId = (0, http_1.optUuid)(body, "league_id");
    if (!leagueId)
        throw new errors_1.ApiError(400);
    const email = (0, http_1.str)(body, "email");
    const validFor = (0, http_1.optInterval)(body, "valid_for");
    const row = await (0, db_1.asCaller)((0, session_1.callerFrom)(req), async (tx) => {
        const r = await tx.query(`select invite_id, token
         from app.platform_invite_admin($1::uuid, $2, coalesce($3::interval, interval '14 days'))`, [leagueId, email, validFor]);
        return r.rows[0] ?? null;
    });
    if (!row)
        throw new errors_1.ApiError(500);
    return (0, http_1.json)({ invite_id: row.invite_id, token: row.token, shown_once: true }, 201);
});
