#!/usr/bin/env node
/**
 * Compile product/hub/lib into api/_lib as CommonJS, for the Vercel functions.
 *
 *   node scripts/sync-api-lib.mjs            build
 *   node scripts/sync-api-lib.mjs --check    exit non-zero on drift
 *
 * WHY A COPY AT ALL. The data layer is TypeScript written for the hub, and it
 * is the tested one: 67 assertions, including the pooled-connection identity
 * leak. The Vercel functions must run THAT code and not a second hand-written
 * version of it, because a second version is a second security model. Same
 * argument as scripts/sync-engine.js -- one source, a generated copy, and a
 * --check that fails when they drift.
 *
 * WHY COMMONJS. api/save-playbook.js and api/feedback.js are CommonJS and are
 * live. Adding "type": "module" at the root would break both. Compiling to CJS
 * lets the new handlers `require()` the tested code and leaves the two working
 * functions alone.
 *
 * THE OUTPUT IS COMMITTED, on purpose. Vercel builds `api/` from the repo with
 * no build step in this project; a generated directory that only exists after
 * someone runs a script is a directory that will be missing in production. It
 * carries a header saying not to edit it.
 */
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, rmSync, mkdirSync, statSync, existsSync, cpSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const HUB = join(ROOT, "product", "hub");
const OUT = join(ROOT, "api", "_lib");
// Hand-written and NOT generated: it bridges Node (req,res) to Web
// Request/Response and has no TypeScript counterpart. Wiping it on every sync
// would delete the only thing that lets the tested handlers run on Vercel.
const KEEP = new Set(["adapter.js"]);
const TMP = join(HUB, ".api-build");
const check = process.argv.includes("--check");

const tsc = join(HUB, "node_modules", ".bin", "tsc");
if (!existsSync(tsc)) {
  console.error("tsc is not installed. Run: cd product/hub && npm install");
  process.exit(1);
}

const CONFIG = {
  compilerOptions: {
    target: "ES2022",
    lib: ["esnext"],
    module: "commonjs",
    moduleResolution: "node",
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    noEmit: false,
    declaration: false,
    outDir: ".api-build",
    rootDir: "lib",
  },
  include: ["lib/**/*.ts"],
};
writeFileSync(join(HUB, "tsconfig.api.json"), JSON.stringify(CONFIG, null, 2) + "\n");

rmSync(TMP, { recursive: true, force: true });
execFileSync(tsc, ["-p", join(HUB, "tsconfig.api.json")], { cwd: HUB, stdio: "inherit" });

const HEADER =
  "/* GENERATED by scripts/sync-api-lib.mjs from product/hub/lib. Do not edit.\n" +
  "   The TypeScript is the source and is what the 67 tests in\n" +
  "   product/hub/test/api.test.mjs attack. `--check` fails if these drift. */\n";

function stamp(dir) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { stamp(p); continue; }
    if (!p.endsWith(".js")) continue;
    const src = readFileSync(p, "utf8");
    if (!src.startsWith("/* GENERATED")) writeFileSync(p, HEADER + src);
  }
}
stamp(TMP);

function listing(dir, base = "") {
  const out = [];
  for (const e of readdirSync(dir).sort()) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { out.push(...listing(p, base + e + "/")); continue; }
    if (!base && KEEP.has(e)) continue;
    out.push([base + e, readFileSync(p, "utf8")]);
  }
  return out;
}

const built = listing(TMP);
const current = existsSync(OUT) ? listing(OUT) : [];
const same =
  built.length === current.length &&
  built.every(([n, c], i) => current[i] && current[i][0] === n && current[i][1] === c);

if (check) {
  rmSync(TMP, { recursive: true, force: true });
  if (!same) {
    console.error("DRIFT  api/_lib does not match product/hub/lib. Run: node scripts/sync-api-lib.mjs");
    process.exit(1);
  }
  console.log("In sync — api/_lib matches product/hub/lib (" + built.length + " files).");
} else {
  const kept = [];
  for (const k of KEEP) {
    const p = join(OUT, k);
    if (existsSync(p)) kept.push([k, readFileSync(p, "utf8")]);
  }
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  cpSync(TMP, OUT, { recursive: true });
  for (const [k, c] of kept) writeFileSync(join(OUT, k), c);
  rmSync(TMP, { recursive: true, force: true });
  console.log((same ? "Already in sync — " : "Updated — ") + built.length + " files in api/_lib.");
}
